"""empty message

Revision ID: 253bc85c3790
Revises: 61591e8c08b0
Create Date: 2025-01-16 12:15:50.102863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253bc85c3790'
down_revision = '61591e8c08b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
