"""empty message

Revision ID: 84ff3604b6da
Revises: 253bc85c3790
Create Date: 2025-01-16 23:19:19.909144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ff3604b6da'
down_revision = '253bc85c3790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('sem', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sem')
    )
    op.drop_table('role')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_name')
        batch_op.drop_index('ix_user_user_email')
        batch_op.drop_index('ix_user_user_name')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_last_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_ip', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_host', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_inst', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_disc', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_role_id', sa.INTEGER(), nullable=True),
    sa.Column('user_email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('user_confirmed', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_user_name', ['user_name'], unique=1)
        batch_op.create_index('ix_user_user_email', ['user_email'], unique=1)
        batch_op.create_index('ix_user_name', ['name'], unique=1)

    op.create_table('role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('disc')
    # ### end Alembic commands ###
